### ISSUE TITLE
Error in `mapped_discrete()`: ! Can't convert `x` <labelled> to <double>.

### ISSUE THREAD

**Issue by proshano** [kassambara/ggpubr#511] opened 2022-11-14 18:31 UTC
I hope you can help with the error below:

Error in `mapped_discrete()`:
! Can't convert `x` <labelled> to <double>.
---
Backtrace:
    1. ggpubr::ggarrange(...)
  2. purrr::map(...)
  3. ggpubr (local) .f(.x[[i]], ...)
  4. cowplot::plot_grid(plotlist = plotlist, ...)
  5. cowplot::align_plots(...)
  6. base::lapply(...)
  7. cowplot (local) FUN(X[[i]], ...)
  9. cowplot:::as_gtable.default(x)
 11. cowplot:::as_grob.ggplot(plot)
 12. ggplot2::ggplotGrob(plot)
 17. ggplot2:::ggplot_build.ggplot(x)
 18. layout$map_position(data)
 19. ggplot2 (local) map_position(..., self = self)
 20. base::lapply(...)
 21. ggplot2 (local) FUN(X[[i]], ...)
 22. ggplot2:::scale_apply(layer_data, x_vars, "map", SCALE_X, self$panel_scales_x)
 23. base::lapply(...)
 24. ggplot2 (local) FUN(X[[i]], ...)
 25. base::lapply(...)
 26. ggplot2 (local) FUN(X[[i]], ...)
 27. scales[[i]][[method]](data[[var]][scale_index[[i]]])
 28. ggplot2 (local) map(..., self = self)
 29. ggplot2:::mapped_discrete(x)

**Comment by proshano** [comment] 2022-11-14 18:32
ggplot 3.4.0
ggpubr 0.5

**Comment by proshano** [comment] 2022-11-14 18:34
Backtrace:
     ▆
  1. ├─ggpubr::ggarrange(...)
  2. │ └─purrr::map(...)
  3. │   └─ggpubr (local) .f(.x[[i]], ...)
  4. │     └─cowplot::plot_grid(plotlist = plotlist, ...)
  5. │       └─cowplot::align_plots(...)
  6. │         └─base::lapply(...)
  7. │           └─cowplot (local) FUN(X[[i]], ...)
  8. │             ├─cowplot::as_gtable(x)
  9. │             └─cowplot:::as_gtable.default(x)
 10. │               ├─cowplot::as_grob(plot)
 11. │               └─cowplot:::as_grob.ggplot(plot)
 12. │                 └─ggplot2::ggplotGrob(plot)
 13. │                   ├─ggplot2::ggplot_gtable(ggplot_build(x))
 14. │                   │ └─ggplot2:::attach_plot_env(data$plot$plot_env)
 15. │                   │   └─base::options(ggplot2_plot_env = env)
 16. │                   ├─ggplot2::ggplot_build(x)
 17. │                   └─ggplot2:::ggplot_build.ggplot(x)
 18. │                     └─layout$map_position(data)
 19. │                       └─ggplot2 (local) map_position(..., self = self)
 20. │                         └─base::lapply(...)
 21. │                           └─ggplot2 (local) FUN(X[[i]], ...)
 22. │                             └─ggplot2:::scale_apply(layer_data, x_vars, "map", SCALE_X, self$panel_scales_x)
 23. │                               └─base::lapply(...)
 24. │                                 └─ggplot2 (local) FUN(X[[i]], ...)
 25. │                                   └─base::lapply(...)
 26. │                                     └─ggplot2 (local) FUN(X[[i]], ...)
 27. │                                       └─scales[[i]][[method]](data[[var]][scale_index[[i]]])
 28. │                                         └─ggplot2 (local) map(..., self = self)
 29. │                                           └─ggplot2:::mapped_discrete(x)
 30. │                                             ├─ggplot2:::new_mapped_discrete(vec_cast(x, double()))
 31. │                                             │ ├─vctrs::vec_assert(as.vector(x), double())
 32. │                                             │ │ └─vctrs:::vec_is_vector(x)
 33. │                                             │ └─base::as.vector(x)
 34. │                                             └─vctrs::vec_cast(x, double())
 35. └─vctrs (local) `<fn>`()
 36.   └─vctrs::vec_default_cast(...)
 37.     ├─base::withRestarts(...)
 38.     │ └─base (local) withOneRestart(expr, restarts[[1L]])
 39.     │   └─base (local) doWithOneRestart(return(expr), restart)
 40.     └─vctrs::stop_incompatible_cast(...)
 41.       └─vctrs::stop_incompatible_type(...)
 42.         └─vctrs:::stop_incompatible(...)
 43.           └─vctrs:::stop_vctrs(...)
 44.             └─rlang::abort(message, class = c(class, "vctrs_error"), ..., call = vctrs_error_call(call))

**Comment by kassambara** [comment] 2022-11-14 20:17
I can't reproduce this issue. Would you please provide a reproducible example with session info ?

**Comment by kassambara** [comment] 2022-11-21 19:33
closing this issue because of missing reproducible example

**Closed by kassambara** 2022-11-21 19:33 UTC
