### ISSUE TITLE
position_dodge does not work properly for jitter

### ISSUE THREAD

**Issue by akindtdunjko** [kassambara/ggpubr#95] opened 2018-06-28 13:54 UTC
when I use position_dodge(0.9) for the bars it does separate the bars next to each other, but the added error bars and jittered dots are not in the middle of the bars.

**Comment by kassambara** [comment] 2018-06-29 05:44
Please, provide a reproducible example so that we can help

**Comment by akindtdunjko** [comment] 2018-06-29 07:50
sorry, here you go: 

```

df1 = data.frame("group1" = rnorm(24, 20, sd = 2), 
                 "group2" = rnorm(24, 30),
                 "group3" = rnorm(24, 40), 
                 "group4" = rnorm(24, 35) 
                 
)
df1[1:6,] = df1[1:6,]/2
df1[7:12,] = df1[1:6,]/3


df1$Treatment = rep(c("WT", paste("Tr", 1:3, sep = "")), each = 6)

dfm = melt(df1, id.vars = "Treatment")
ggbarplot(dfm, x = "variable", y = "value", add = c("mean_sd", "point"),
          color = "Treatment", fill = "Treatment", alpha = 0.5, position = position_dodge(), add.params = list(color = "Treatment"))


````

![image](https://user-images.githubusercontent.com/39906954/42080116-d66d3fea-7b81-11e8-86f0-280642b87eb2.png)


 you can see, that the position_dodge() does not work properly with the dots and error bars as they are not aligned in the middle

**Comment by akindtdunjko** [comment] 2018-06-29 07:51
I did not mean to close it.....

**Comment by kassambara** [comment] 2018-06-30 07:32
With the latest developmental version of ggpubr, it works as expected:

```r

library(reshape2)
library(ggpubr)

df1 = data.frame("group1" = rnorm(24, 20, sd = 2), 
                 "group2" = rnorm(24, 30),
                 "group3" = rnorm(24, 40), 
                 "group4" = rnorm(24, 35) 
                 
)
df1[1:6,] = df1[1:6,]/2
df1[7:12,] = df1[1:6,]/3


df1$Treatment = rep(c("WT", paste("Tr", 1:3, sep = "")), each = 6)

dfm = melt(df1, id.vars = "Treatment")
ggbarplot(dfm, x = "variable", y = "value", add = c("mean_sd", "point"),
          color = "Treatment", fill = "Treatment", alpha = 0.5,
          position = position_dodge(), add.params = list(color = "Treatment")
          )

```

![rplot31](https://user-images.githubusercontent.com/3313355/42122861-7951ba62-7c48-11e8-8202-8db2b5b0e56b.png)

**Comment by akindtdunjko** [comment] 2018-07-03 08:33
it works well for 3+ groups, but for three it does not. my session info is pasted below

```
Session info -------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.0 (2018-04-23)
 system   x86_64, darwin15.6.0        
 ui       RStudio (1.1.453)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       Europe/Amsterdam            
 date     2018-07-03                  

Packages -----------------------------------------------------------------------------------------------------------------------------------------------------
 package    * version   date       source                            
 assertthat   0.2.0     2017-04-11 CRAN (R 3.5.0)                    
 base       * 3.5.0     2018-04-24 local                             
 bindr        0.1.1     2018-03-13 CRAN (R 3.5.0)                    
 bindrcpp     0.2.2     2018-03-29 CRAN (R 3.5.0)                    
 bitops       1.0-6     2013-08-17 CRAN (R 3.5.0)                    
 caTools      1.17.1    2014-09-10 CRAN (R 3.5.0)                    
 cellranger   1.1.0     2016-07-27 CRAN (R 3.5.0)                    
 colorspace   1.3-2     2016-12-14 CRAN (R 3.5.0)                    
 compiler     3.5.0     2018-04-24 local                             
 curl         3.2       2018-03-28 CRAN (R 3.5.0)                    
 datasets   * 3.5.0     2018-04-24 local                             
 devtools     1.13.6    2018-06-27 CRAN (R 3.5.0)                    
 digest       0.6.15    2018-01-28 CRAN (R 3.5.0)                    
 dplyr      * 0.7.6     2018-06-29 CRAN (R 3.5.1)                    
 gdata        2.18.0    2017-06-06 CRAN (R 3.5.0)                    
 ggplot2    * 2.2.1     2016-12-30 CRAN (R 3.5.0)                    
 ggpubr     * 0.1.7.999 2018-07-03 Github (kassambara/ggpubr@8f7fa67)
 ggsignif   * 0.4.0     2017-08-03 CRAN (R 3.5.0)                    
 git2r        0.21.0    2018-01-04 CRAN (R 3.5.0)                    
 glue         1.2.0     2017-10-29 CRAN (R 3.5.0)                    
 gplots     * 3.0.1     2016-03-30 CRAN (R 3.5.0)                    
 graphics   * 3.5.0     2018-04-24 local                             
 grDevices  * 3.5.0     2018-04-24 local                             
 grid       * 3.5.0     2018-04-24 local                             
 gridExtra  * 2.3       2017-09-09 CRAN (R 3.5.0)                    
 gtable       0.2.0     2016-02-26 CRAN (R 3.5.0)                    
 gtools       3.8.1     2018-06-26 CRAN (R 3.5.0)                    
 httr         1.3.1     2017-08-20 CRAN (R 3.5.0)                    
 KernSmooth   2.23-15   2015-06-29 CRAN (R 3.5.0)                    
 labeling     0.3       2014-08-23 CRAN (R 3.5.0)                    
 lazyeval     0.2.1     2017-10-29 CRAN (R 3.5.0)                    
 magrittr   * 1.5       2014-11-22 CRAN (R 3.5.0)                    
 memoise      1.1.0     2017-04-21 CRAN (R 3.5.0)                    
 methods    * 3.5.0     2018-04-24 local                             
 munsell      0.5.0     2018-06-12 CRAN (R 3.5.0)                    
 pillar       1.2.3     2018-05-25 CRAN (R 3.5.0)                    
 pkgconfig    2.0.1     2017-03-21 CRAN (R 3.5.0)                    
 plyr         1.8.4     2016-06-08 CRAN (R 3.5.0)                    
 purrr        0.2.5     2018-05-29 CRAN (R 3.5.0)                    
 R6           2.2.2     2017-06-17 CRAN (R 3.5.0)                    
 Rcpp         0.12.17   2018-05-18 CRAN (R 3.5.0)                    
 readxl     * 1.1.0     2018-04-20 CRAN (R 3.5.0)                    
 reshape2   * 1.4.3     2017-12-11 CRAN (R 3.5.0)                    
 rlang        0.2.1     2018-05-30 CRAN (R 3.5.0)                    
 scales       0.5.0     2017-08-24 CRAN (R 3.5.0)                    
 stats      * 3.5.0     2018-04-24 local                             
 stringi      1.2.3     2018-06-12 CRAN (R 3.5.0)                    
 stringr      1.3.1     2018-05-10 CRAN (R 3.5.0)                    
 tibble       1.4.2     2018-01-22 CRAN (R 3.5.0)                    
 tidyselect   0.2.4     2018-02-26 CRAN (R 3.5.0)                    
 tools        3.5.0     2018-04-24 local                             
 utils      * 3.5.0     2018-04-24 local                             
 withr        2.1.2     2018-03-15 CRAN (R 3.5.0)                    
```

**Comment by kassambara** [comment] 2018-07-10 05:55
It works for me.

Install the latest version of ggplot2 (3.0.0) and try again.

```r
library(ggpubr)
df1 = data.frame("group1" = rnorm(24, 20, sd = 2), 
                 "group2" = rnorm(24, 30),
                 "group3" = rnorm(24, 40)
                 
)

df1[1:6,] = df1[1:6,]/2
df1[7:12,] = df1[1:6,]/3

df1$Treatment = rep(c(paste("Tr", 1:3, sep = "")), each = 8)

dfm = melt(df1, id.vars = "Treatment")
ggbarplot(dfm, x = "variable", y = "value", add = c("mean_sd", "point"),
          color = "Treatment", fill = "Treatment", alpha = 0.5,
          position = position_dodge(), add.params = list(color = "Treatment")
)
````

![rplot34](https://user-images.githubusercontent.com/3313355/42491812-a8c99348-8416-11e8-9767-b25425efe222.png)

**Comment by kassambara** [comment] 2018-07-23 20:45
I think that we can close this issue

**Closed by kassambara** 2018-07-23 20:45 UTC
