### ISSUE TITLE
Adjust digits for R^2 values

### ISSUE THREAD

**Issue by icer182** [kassambara/ggpubr#239] opened 2020-02-11 22:19 UTC
Hi @kassambara! I have plotted two regression lines on a scatterplot by the grouping variable of sex and generated 2 separate R^2 values for each line using 

(stat_poly_eq(aes(color = Sex, label = paste(..rr.label..)), formula = y ~ x, rr.digits = 2, parse = TRUE, size = 12). 

However, I am unable to adjust the decimal places for each R^2 value, independently. Optimally, I would like to be able to set R1^2 to 3 digits and R2^2 to 2 digits. I have scoured the internet and have not been able to find a solution to this. Please let me know if anything is currently built into the system. Thank you.

**Comment by kassambara** [comment] 2020-02-12 20:25
duplicate of #114

**Closed by kassambara** 2020-02-12 20:25 UTC
