### ISSUE TITLE
Brackets positioning messed up

### ISSUE THREAD

**Issue by pdeninis** [kassambara/ggpubr#386] opened 2021-03-24 23:22 UTC
I made this plot some time ago.

![image](https://user-images.githubusercontent.com/35506062/112392584-edd77d80-8cf9-11eb-9227-3803abe73ad7.png)

As you can see, the brackets were perfectly positioned.

Today, after updating some packages - among which maybe ggpubr too - I have used the same code to redo the plot, and this is the result:

![image](https://user-images.githubusercontent.com/35506062/112392960-908ffc00-8cfa-11eb-84d8-bee969e8f006.png)

Have you some idea about what happened?
It seems to me that the position computed for the first group has been used for the bracket of the third one, the position for the second has been used for the first group and that of the third group ended up below the second one...

Thanks.

**Comment by kassambara** [comment] 2021-03-29 10:39
can you please provide a reproducible  code ?

**Comment by pdeninis** [comment] 2021-03-29 22:47
Before sending the code I have run it on R 4.0.2.
There the function works properly.

The graph above had been run in R 3.6.1, but all the packages had been updated.
Maybe that was causing the issue?

Anyway, thank you for your package, and sorry for the false alarm!

**Comment by pdeninis** [comment] 2021-04-10 11:07
Hi Alboukadel,

I have installed R 4.0.5 with all new packages.
Unfortunately the result is again the preceding one:
![R4 0 5](https://user-images.githubusercontent.com/35506062/114267683-6bd79c00-99fd-11eb-9ee9-cb19476e9183.jpg)

**Comment by pdeninis** [comment] 2021-05-06 13:49
Hi Aboukadel,
I apologize since the code I posted was incomplete: I didn't realized.

I fixed it and now it 's working.



```
library(rstatix)
library(ggpubr)
library(tidyverse)
library(emmeans)

test <-
structure(list(TREAT = structure(c(1L, 1L, 1L, 1L, 1L, 1L, 1L,
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 2L, 2L, 2L, 2L,
2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L,
3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L,
3L, 3L, 3L, 3L), .Label = c("CAF+L-PRF", "CAF+SCTG", "CAF"), class = "factor"),
GT_PRE = c(0.75574694999807401, 0.51377910615185396, 1.0502637416109999,
1.0529533576294099, 0.77628725655794695, 1.3024972039373,
1.29771873358056, 0.73223467651353302, 1.22548037918804,
0.70149281871692604, 1.2311467357729, 0.46592903526631801,
1.3053788021822601, 1.12747309255473, 1.0169638634654701,
1.46867879701079, 1.3887822192828201, 1.65913611414644, 0.94901409760925304,
0.68205176445635995, 0.75644708395693905, 1.3616212413887501,
0.80383327604294097, 0.83230193955718301, 0.55268821321151596,
1.0519620174778901, 0.85095516359899204, 1.4247162705459,
1.1978302782129999, 1.2008821995972401, 1.31677721147256,
1.0739940342185701, 0.56676654709428298, 0.758831881198758,
1.3437548491340201, 0.65625798126018697, 1.3642652746664301,
0.55179612606860495, 0.65226664683987401, 2.0293138768199199,
0.51765428550824999, 1.44939808663943, 1.4351805942674301,
0.79060226551773405, 1.30006971367069, 0.43285805219381801,
1.3771237596136201, 1.3424065948697199, 1.36634025195904,
0.91555239568191604, 1.3080349133981199, 0.91134124601174404,
0.95967271975461899, 0.30459336422795502, 1.2390723762771501,
1.03821439983465, 1.5266871239430899, 0.55959657184888001,
0.69628740796219102), GT_CH = c(1.5037592104009601, 0.37708778079514599,
0.45235941364484999, 1.47467219782683, 1.38937977222239,
0.38294772070726102, 0.53507913236442095, 0.51621910868277399,
1.5460292374508999, 0.57829211304672301, 0.78354210363062204,
1.27983126105837, 0.65175904047684896, 0.64853873777691096,
1.67261015217373, 0.37028803346980099, 0.80590716432980702,
0.73263456408220995, 0.70055849005411996, 1.2038454466045301,
0.85383942914639899, 1.2033768482948399, 0.78518775133726304,
1.1532594566047101, 0.95706532630658103, 1.09035994424734,
0.96203108898110901, 0.87836955861037402, 1.1076942857758001,
0.91892022371736704, 0.91944572314908601, 1.23935985446435,
0.96783791234521399, 0.864725786870432, 0.91795738647703295,
0.960009924034951, 1.1132551653164899, 1.0893876577154999,
0.81407123000060999, 0.45680795412162301, 0.36293109415511299,
0.302514131741624, 0.209648306428177, 0.33702680696005899,
0.34665042370576998, 0.24027654459536399, 0.18939783794448001,
0.29675637555508699, 0.50588365046038697, 0.38409189747421602,
0.37343044300995298, 0.215801805337029, 0.25930223824998,
0.35320250264132103, 0.25379570499944498, 0.22825343224356601,
0.31567886771034698, 0.49647580510056799, 0.172074177565914
), Subgroup = structure(c(1L, 1L, 1L, 1L, 1L, 2L, 2L, 1L,
1L, 1L, 2L, 1L, 2L, 1L, 1L, 2L, 2L, 2L, 1L, 1L, 1L, 2L, 1L,
1L, 1L, 1L, 1L, 2L, 1L, 1L, 2L, 1L, 1L, 1L, 2L, 1L, 2L, 1L,
1L, 2L, 1L, 2L, 2L, 1L, 2L, 1L, 2L, 2L, 2L, 1L, 2L, 1L, 1L,
1L, 2L, 1L, 2L, 1L, 1L), .Label = c("LOW", "HIGH"), class = "factor")), row.names = c(1L,
2L, 3L, 4L, 5L, 6L, 7L, 8L, 9L, 10L, 11L, 12L, 13L, 14L, 15L,
16L, 18L, 19L, 20L, 21L, 22L, 23L, 24L, 25L, 26L, 27L, 28L, 29L,
30L, 31L, 32L, 33L, 34L, 35L, 36L, 37L, 38L, 39L, 40L, 41L, 42L,
43L, 44L, 45L, 46L, 47L, 48L, 49L, 50L, 51L, 52L, 53L, 54L, 55L,
56L, 57L, 58L, 59L, 60L), class = "data.frame")

res.aovo<-test %>% anova_test(GT_CH ~ TREAT * Subgroup)
pwco <- test %>% group_by(TREAT) %>% emmeans_test(GT_CH ~ Subgroup, p.adjust.method = "bonferroni")
pwco <- pwco %>% add_xy_position(x = "TREAT")
bxpo <- ggpubr::ggboxplot(test, x = "TREAT", y = "GT_CH", color = "Subgroup", palette = "jco" )+ labs(y = "Gingival Thickness Increase (mm)") + labs(title = "GT Increase Factorial ANOVA Treatment * Subgroup (Baseline cutoff = 1.2)", subtitle="(without case 17)")
bxpo + stat_pvalue_manual(pwco) + labs( subtitle = get_test_label(res.aovo, detailed = TRUE), caption = get_pwc_label(pwco)) + labs(y = "Gingival Thickness Increase (mm)") + labs(title = " GT Increase ~ Treatment * Subgroup (Baseline cutoff = 1.2) w/o case `17")
```

Unfortunately it does still not work.

**Comment by kassambara** [comment] 2022-11-27 11:08
The issue is caused by broom:tidy() at https://github.com/kassambara/rstatix/blob/c36a70f22a8aeac58ffc9190decd70db18d0ebd1/R/emmeans_test.R#L135, which  is changing factor to character since version broom version 0.5.6.

**Comment by pdeninis** [comment] 2022-11-27 11:53
Weel done, the culprit was found.
Have you thought a workaround?
Might A solution be to use the old version by renaming and including it in your package?

**Comment by kassambara** [comment] 2022-11-27 15:09
fixed now, thanks for reporting the issue and for your reproducible scripts. Main changes done at: https://github.com/kassambara/rstatix/pull/170

You need the latest dev versions of ggpubr and rstatix

**Closed by kassambara** 2022-11-27 15:09 UTC

**Comment by pdeninis** [comment] 2022-11-30 21:22
Hi Alboukadel,
I have installed R 4.2.2 with ggpubr and rstatix. It doesn't work.

I checked the version of the installed packages and got:
```
> packageVersion("ggpubr")
[1] ‘0.5.0’
> packageVersion("rstatix")
[1] ‘0.7.1’
```
I read on your link that rstatix 0.7.1.999 is needed, but I can't find it. 
What exactly should I do?

**Comment by kassambara** [comment] 2022-11-30 21:26
Please consider installing the latest dev version of the two packages as follow:

```r
devtools::install_github("kassambara/rstatix")
devtools::install_github("kassambara/ggpubr")
```

After installation, everythyng should work. Please let me know if this is not case.

**Comment by pdeninis** [comment] 2022-11-30 21:41
Thanks! Now it is OK.
