### ISSUE TITLE
Pass data parameter to Comparisons in stat_compare_means

### ISSUE THREAD

**Issue by emcnerny** [kassambara/ggpubr#48] opened 2017-11-09 17:05 UTC
I would like to be able to use comparisons for a subset of the data passed to stat_compare_means. Right now you can do this to compare means against a reference group, but not for specified comparisons. For example, here I'm testing against the lowest dose only for the VC group:
```R
df <- ToothGrowth
df$dose <- as.factor(df$dose)
df.VC <- df[df$supp == "VC",]
#Plot using ref.group
ggbarplot(
  df,
  "dose",
  "len",
  color = "supp",
  add = c("point", "mean_sd"),
  xlab = "dose",
  ylab = "len",
  position = position_dodge(0.72)
  ) + stat_compare_means(
    data = df.VC,
    method = "t.test",
    ref.group = "0.5",
    label = "p.format"
  )
```
Which produces:
![image](https://user-images.githubusercontent.com/4778287/32618741-8aa3b2fc-c546-11e7-97bd-923ec670587a.png)

But this does not work for comparisons (the data parameter is ignored, so it pools the supp groups):
```R
#Plot using comparisons - should have same values, but ignores subsetted data (df.VC)
mycomparisons = list(c("0.5", "1"), c("0.5", "2"))
ggbarplot(
  df,
  "dose",
  "len",
  color = "supp",
  add = c("point", "mean_sd"),
  xlab = "dose",
  ylab = "len",
  position = position_dodge(0.72)
) + stat_compare_means(
  data = df.VC,
  method = "t.test",
  comparisons = mycomparisons
)
```
Which produces:
![image](https://user-images.githubusercontent.com/4778287/32618397-a1101f2c-c545-11e7-9f0e-aec6afb464af.png)

A separate but related issue, any attempt to pass a label type with comparisons doesn't have the expected result: 
```R
#Plot using comparisons - should have same values, but ignores data
mycomparisons = list(c("0.5", "1"), c("0.5", "2"))
ggbarplot(
  df,
  "dose",
  "len",
  color = "supp",
  add = c("point", "mean_sd"),
  xlab = "dose",
  ylab = "len",
  position = position_dodge(0.72)
) + stat_compare_means(
  data = df.VC,
  method = "t.test",
  comparisons = mycomparisons,
  label = "p.format"
)
```
![image](https://user-images.githubusercontent.com/4778287/32618577-24ab52f2-c546-11e7-8bd3-8bc771bcfce7.png)

**Comment by kassambara** [comment] 2017-11-09 18:31
Thank you for this well written and reproducible bug report.

Fixed, now!

Install the latest developmental version and kindly confirm that it works.

**Comment by emcnerny** [comment] 2017-11-09 18:53
Works great, thanks!

**Comment by kassambara** [comment] 2017-11-09 18:53
so we can close this issue!

**Comment by emcnerny** [comment] 2017-11-09 19:06
Would it be possible to make it so additional params can be passed through to geom_signif? It would make it possible to adjust xmin/xmax and y_position so the tips fall over the correct bars when using subsetted data like in this example.

**Comment by ousabd** [comment] 2018-06-29 18:52
Thanks for this great package kassambara.

I was wondering whether emcnerny's last proposition (adjusting the x position so the tips fall over dodged bars in subsetted data) was feasible ?

**Closed** 2018-07-10 21:01 UTC

**Comment by bznes** [comment] 2019-03-11 21:59
This is a great package but I am having the same problem.  I want to overlay p-values for a subset of comparisons ONLY to the treated data to a base plot that looks like this:

`ggbarplot(d=d, x = "Group",y="response",color="Treatment",add = "mean_se",position = position_dodge(0.8))`
![baseplot](https://user-images.githubusercontent.com/48456383/54160072-32926380-4414-11e9-9fe1-dc0dcc80d176.jpeg)

When I add stat_compare_means for the treated plot I get this:
`  my_comparisons=list(c("C1","C2"),
                      c("A","C2"),
                      c("C2","B"),
                      c("C2","D"),
                      c("D","E"),
                      c("D","F"))
  d.treated <- d[d$Treatment == "treated",]
  ggbarplot(d=d, x = "Group",y="response",color="Treatment",add = "mean_se",position = position_dodge(0.8))+
    stat_compare_means(d.treated,comparisons=my_comparisons)`

![baseplot_statcompare](https://user-images.githubusercontent.com/48456383/54160201-8b61fc00-4414-11e9-9042-ae373f09072b.jpeg)

However, this is ignoring use of the treated group for stat_compare_means.  When I run as facet I see the p-values I actually want displayed on the plot.  

`  ggbarplot(d=d, x = "Group",y="response",color="Treatment",facet.by="Treatment",add = "mean_se",position = position_dodge(0.8))+
    stat_compare_means(comparisons=my_comparisons)`
![baseplot with facet](https://user-images.githubusercontent.com/48456383/54160458-2d81e400-4415-11e9-850a-3c8e2d775f7e.jpeg)

Is it possible to get the data from the right panel on my first image?  Per the above solution I updated all my packages and it still is not working.  Can I overlay two ggbarplots like geom_line and geom_point in ggplot?  I haven't been able to get that to work.

Thanks!

**Comment by bznes** [comment] 2019-03-15 21:58
Problem solved...despite a recent download, sessionInfo() revealed I was running an older version of ggpubr package, updating to ggpubr_0.2 fixed my problem.  Now my question is if you can recenter the comparison brackets over the group being compared (treated, not centered between the two treatment levels).
![image](https://user-images.githubusercontent.com/48456383/54464098-f8d69b00-473a-11e9-8a90-eeffad25f5e2.png)
