### ISSUE TITLE
Text element requires non-NULL value for 'angle'

### ISSUE THREAD

**Issue by jcpsantiago** [kassambara/ggpubr#14] opened 2017-07-27 15:06 UTC
Using ggarrange always results in the error:
`Error in element_grob.element_text(el, ...) :
 Text element requires non-NULL value for 'angle'.`

I'm using the latest github version of ggpubr and all my packages are up-to-date as of today (27th of July, 2017).

To reproduce the error simply run the example code in the ggarrange help page.

**Comment by kassambara** [comment] 2017-07-27 15:20
Hi,

This error is not reproducible on my computer. It seems to be related with ggplot2. 

Please post your session info, which can be obtained using a command like `devtools::session_info(c("ggpubr", "ggplot2"))`


My session info:

<pre>
Session info ----------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.2 (2016-10-31)
 system   x86_64, darwin13.4.0        
 ui       RStudio (1.0.136)           
 language (EN)                        
 collate  fr_FR.UTF-8                 
 tz       Europe/Paris                
 date     2017-07-27                  

Packages --------------------------------------------------------------------------------------
 package      * version    date       source                                
 assertthat     0.2.0      2017-04-11 cran (@0.2.0)                         
 BH             1.62.0-1   2016-11-19 CRAN (R 3.3.2)                        
 bindr          0.1        2016-11-13 cran (@0.1)                           
 bindrcpp       0.2        2017-06-17 cran (@0.2)                           
 colorspace     1.3-2      2016-12-14 CRAN (R 3.3.2)                        
 cowplot        0.7.0      2016-10-28 CRAN (R 3.3.0)                        
 dichromat      2.0-0      2013-01-24 CRAN (R 3.3.0)                        
 digest         0.6.12     2017-01-27 cran (@0.6.12)                        
 dplyr          0.7.1      2017-06-22 CRAN (R 3.3.2)                        
 ggplot2      * 2.2.1      2016-12-30 CRAN (R 3.3.2)                        
 ggpubr       * 0.1.4.999  <NA>       local                                 
 ggrepel        0.6.5      2016-11-24 CRAN (R 3.3.2)                        
 ggsci          2.7        2017-06-12 cran (@2.7)                           
 ggsignif       0.3.0.9000 2017-06-26 Github (Artjom-Metro/ggsignif@d7aab9e)
 glue           1.1.1      2017-06-21 cran (@1.1.1)                         
 graphics     * 3.3.2      2016-10-31 local                                 
 grDevices    * 3.3.2      2016-10-31 local                                 
 grid           3.3.2      2016-10-31 local                                 
 gridExtra      2.2.1      2016-02-29 CRAN (R 3.3.0)                        
 gtable         0.2.0      2016-02-26 CRAN (R 3.3.0)                        
 labeling       0.3        2014-08-23 CRAN (R 3.3.0)                        
 lazyeval       0.2.0      2016-06-12 CRAN (R 3.3.0)                        
 magrittr     * 1.5        2014-11-22 CRAN (R 3.3.0)                        
 MASS           7.3-45     2016-04-21 CRAN (R 3.3.2)                        
 methods      * 3.3.2      2016-10-31 local                                 
 munsell        0.4.3      2016-02-13 CRAN (R 3.3.0)                        
 pkgconfig      2.0.1      2017-03-21 cran (@2.0.1)                         
 plogr          0.1-1      2016-09-24 CRAN (R 3.3.0)                        
 plyr           1.8.4      2016-06-08 CRAN (R 3.3.0)                        
 purrr          0.2.2.2    2017-05-11 cran (@0.2.2.2)                       
 R6             2.2.2      2017-06-17 cran (@2.2.2)                         
 RColorBrewer   1.1-2      2014-12-07 CRAN (R 3.3.0)                        
 Rcpp           0.12.11    2017-05-22 cran (@0.12.11)                       
 reshape2       1.4.2      2016-10-22 CRAN (R 3.3.0)                        
 rlang          0.1.1      2017-05-18 cran (@0.1.1)                         
 scales         0.4.1      2016-11-09 CRAN (R 3.3.2)                        
 stats        * 3.3.2      2016-10-31 local                                 
 stringi        1.1.5      2017-04-07 cran (@1.1.5)                         
 stringr        1.2.0      2017-02-18 cran (@1.2.0)                         
 tibble         1.3.3      2017-05-28 cran (@1.3.3)                         
 tidyr          0.6.3      2017-05-15 cran (@0.6.3)                         
 tools          3.3.2      2016-10-31 local                                 
 utils        * 3.3.2      2016-10-31 local  
</pre>

**Comment by jcpsantiago** [comment] 2017-07-27 16:02
here you go

```
Session info --------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.1 (2017-06-30)
 system   x86_64, linux-gnu           
 ui       RStudio (1.0.143)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       Europe/Berlin               
 date     2017-07-27                  

Packages ------------------------------------------------------------------------------
 package      * version   date       source                            
 assertthat     0.1       2013-12-06 CRAN (R 3.2.2)                    
 BH             1.58.0-1  2015-05-21 CRAN (R 3.2.2)                    
 bindr          0.1       2016-11-13 CRAN (R 3.4.0)                    
 bindrcpp     * 0.2       2017-06-17 CRAN (R 3.4.0)                    
 colorspace     1.2-6     2015-03-11 CRAN (R 3.2.2)                    
 cowplot        0.7.0     2016-10-28 CRAN (R 3.4.1)                    
 DBI            0.7       2017-06-18 CRAN (R 3.4.0)                    
 dichromat      2.0-0     2013-01-24 CRAN (R 3.2.2)                    
 digest         0.6.8     2014-12-31 CRAN (R 3.2.2)                    
 dplyr        * 0.7.2     2017-07-20 CRAN (R 3.4.1)                    
 ggplot2      * 2.2.1     2016-12-30 CRAN (R 3.4.0)                    
 ggpubr       * 0.1.4.999 2017-07-27 Github (kassambara/ggpubr@cb0f308)
 ggrepel        0.6.5     2016-11-24 CRAN (R 3.4.1)                    
 ggsci          2.7       2017-06-12 CRAN (R 3.4.1)                    
 ggsignif       0.3.0     2017-06-25 CRAN (R 3.4.1)                    
 glue           1.1.1     2017-06-21 CRAN (R 3.4.0)                    
 graphics     * 3.4.1     2017-06-30 local                             
 grDevices    * 3.4.1     2017-06-30 local                             
 grid           3.4.1     2017-06-30 local                             
 gridExtra      2.2.1     2016-02-29 CRAN (R 3.4.0)                    
 gtable         0.1.2     2012-12-05 CRAN (R 3.2.2)                    
 labeling       0.3       2014-08-23 CRAN (R 3.2.2)                    
 lazyeval       0.2.0     2016-06-12 CRAN (R 3.4.0)                    
 magrittr     * 1.5       2014-11-22 CRAN (R 3.2.2)                    
 MASS           7.3-47    2017-02-26 CRAN (R 3.4.1)                    
 methods      * 3.4.1     2017-06-30 local                             
 munsell        0.4.2     2013-07-11 CRAN (R 3.2.2)                    
 pkgconfig      2.0.1     2017-03-21 CRAN (R 3.4.0)                    
 plogr          0.1-1     2016-09-24 CRAN (R 3.4.0)                    
 plyr           1.8.3     2015-06-12 CRAN (R 3.2.2)                    
 proto          0.3-10    2012-12-22 CRAN (R 3.2.2)                    
 purrr        * 0.2.2.2   2017-05-11 CRAN (R 3.4.0)                    
 R6             2.1.1     2015-08-19 CRAN (R 3.2.2)                    
 RColorBrewer   1.1-2     2014-12-07 CRAN (R 3.2.2)                    
 Rcpp           0.12.12   2017-07-15 CRAN (R 3.4.1)                    
 reshape2       1.4.1     2014-12-06 CRAN (R 3.2.2)                    
 rlang          0.1.1     2017-05-18 CRAN (R 3.4.0)                    
 scales         0.4.1     2016-11-09 CRAN (R 3.4.0)                    
 stats        * 3.4.1     2017-06-30 local                             
 stringi      * 1.1.5     2017-04-07 CRAN (R 3.4.0)                    
 stringr        1.2.0     2017-02-18 CRAN (R 3.4.0)                    
 tibble       * 1.3.3     2017-05-28 CRAN (R 3.4.0)                    
 tidyr        * 0.6.3     2017-05-15 CRAN (R 3.4.0)                    
 tools          3.4.1     2017-06-30 local                             
 utils        * 3.4.1     2017-06-30 local 
```

**Comment by jcpsantiago** [comment] 2017-08-02 09:21
This is not happening anymore.. strangely everything is working. Consider it solved ;)

**Comment by kassambara** [comment] 2017-08-02 13:13
So we can close this issue, thanks.

**Closed by kassambara** 2017-08-02 13:13 UTC
