### ISSUE TITLE
pvalue overlap with stat_compare_means

### ISSUE THREAD

**Issue by splaisan** [kassambara/ggpubr#145] opened 2018-12-19 11:30 UTC
Some p-values overlap when plotting horizontally, is there a setting allowing to print values differently?

![screen shot 2018-12-19 at 12 29 38](https://user-images.githubusercontent.com/858516/50217711-c4488280-0389-11e9-972f-645e528e8434.png)

**Comment by kassambara** [comment] 2020-05-24 18:53
duplicate of #179

**Closed by kassambara** 2020-05-24 18:53 UTC
