### ISSUE TITLE
Not possible to change location of pvalues and bars (ggbarplot)

### ISSUE THREAD

**Issue by Zirys1** [kassambara/ggpubr#47] opened 2017-11-03 16:17 UTC
I am unable to change the location of p-value labels and the corresponding lines showing the pairwise comparisons in a barplot using the fill option.
The mean bar heights are negative. Still, the locations of the lines and p-values start at the maximum value for the dependent (y-axis) variable. 
I am not able to change this via "lab.vjust" or "lab.hjust". These two options do nothing.

Is there a possibility to fix this?

Kind regards (and thanks for the wonderful function),
Zirys

**Comment by kassambara** [comment] 2017-11-06 18:33
Would you, please, provide a reproducible example so that I can try it?

You can specify the argument label.y and label.x

**Comment by Zirys1** [comment] 2017-11-06 19:35
Sorry, forgot the example. It is below.
Q: How do I change the y-location of the p-value labels and the corresponding lines that indicate which bars are compared?

seed(123456)
y <- rnorm(100, -5, 5)
t <- c(rep(0, 25), rep(1, 25), rep(2, 25), rep(3, 25))
f <- c(rep(0, 25), rep(1, 25), rep(2, 25), rep(3, 25))
d <- as.data.frame(cbind(y,t,f))

d$f <- factor(d$f, levels = c(0,1,2,3), labels = c("Z", "O", "T", "F"))

library(ggpubr)

cm <- compare_means(y ~ f, d, method = "wilcox.test", p.adjust.method = "none", paired = F)

my_comparisons <- list(c("Z", "O"), c("T", "F"))

ggbarplot(data = d, x = "f", y = "y", add = "mean_ci") +
  stat_compare_means(comparisons = my_comparisons)

**Comment by kassambara** [comment] 2017-11-06 19:59
It works for me:

```r
ggbarplot(data = d, x = "f", y = "y", add = "mean_ci") +
    stat_compare_means(comparisons = my_comparisons, label.y = 2, tip.length = 0.007)
```

![rplot](https://user-images.githubusercontent.com/3313355/32461175-48728d4e-c335-11e7-88b2-48b77ee1db1b.png)

**Comment by Zirys1** [comment] 2017-11-06 20:09
Hm. Sorry, I was using all these options in the ggbarplot function, not in the stat_compare_means one.
Thanks a lot for the answer though!!!

**Comment by kassambara** [comment] 2017-11-06 20:10
ok, so we can close this issue!

**Closed by kassambara** 2017-11-06 20:10 UTC
