### ISSUE TITLE
Custom R2 values 

### ISSUE THREAD

**Issue by ajpelu** [kassambara/ggpubr#202] opened 2019-08-12 17:39 UTC
Hi, 
Thanks for the package. 

I would like to include custom values of R2 to a grouped regression and also p.values. Is there any way to increase (or decrease) the number of digits to display using stat_cor? 

Thanks in advance

**Comment by icer182** [comment] 2020-02-11 22:09
Hi @ajpelu! I was wondering if you ever got this resolved? I am currently looking to do this same thing and have not found anywhere that describes this process yet. I have calculated my own R^2 values for each regression lines so that I could round them independently, but have not figured out a way of displaying these manually calculated values yet. Please let me know if you've figured anything out. @kassambara

**Comment by kassambara** [comment] 2020-02-12 20:43
duplicate of #114: new argument `digits` is now available

**Comment by ajpelu** [comment] 2020-02-12 23:28
Thanks @kassambara @icer182

**Closed** 2020-02-12 23:29 UTC
