### ISSUE TITLE
Suggestion: Showing only significant p-values

### ISSUE THREAD

**Issue by lajoimat** [kassambara/ggpubr#110] opened 2018-09-10 16:48 UTC
Hi,

It would be handy if there was a third label option in stat_compare_means() for showing only the significant p-values or "ns" otherwise.

![image](https://user-images.githubusercontent.com/7004005/45311046-fbd7a100-b4f5-11e8-93b4-15f6cc4103f2.png)

Thanks for that very useful package!

**Comment by kassambara** [comment] 2020-06-01 21:48
duplicate of #204 

This blog posts might be also helpful: [How to Add P-Values onto Basic GGPLOTS](https://www.datanovia.com/en/blog/how-to-add-p-values-onto-basic-ggplots/)

**Closed by kassambara** 2020-06-01 21:48 UTC
