### ISSUE TITLE
Bracket alignment in boxplot with mixed number of conditions

### ISSUE THREAD

**Issue by danielbenjamintorka** [kassambara/ggpubr#326] opened 2020-08-11 15:47 UTC
Dear kassambara,

I want to generate a boxplot in which each study (x-axis) contains a different number of groups and consequently test for significant changes in the means within the studies. However, when studies with different number of groups are used to plot the boxplot, the corresponding brackets that are generated by the stat_pvalue_manual command do not properly align with the boxes in the plot. 

Example for repoduction: 

```R

# Load required packages

library(ggpubr)
library(rstatix)
set.seed(78)

# generate a tibble containing two pairs of studies. Studies from type X contain
# 2 groups, Control and Disease Type 1(CTR / Dis1). Studies from type Y contain 
# 3 groups (CTR / Dis2 / Dis3).

Study <- c(rep("A", 80), rep("B", 120), rep("C", 60), rep("D", 90))
Studytype <- c(rep("X", 200), rep("Y", 150))
Group <- as.factor(c(rep("CTR", 40), rep("Dis1", 40), rep("CTR", 60), rep("Dis1", 60), 
           rep("CTR", 20), rep("Dis2", 20), rep("Dis3", 20), rep("CTR", 30), 
           rep("Dis2", 30), rep("Dis3", 30)))
Values <- as.integer(c(rnorm(40, mean = 5000, sd = 400), 
            rnorm(40, mean = 4000, sd = 610),  
            rnorm(60, mean = 10000, sd = 500),  
            rnorm(60, mean = 8000, sd = 450),  
            rnorm(20, mean = 2000, sd = 650),  
            rnorm(20, mean = 4000, sd = 470),  
            rnorm(20, mean = 2500, sd = 630),  
            rnorm(30, mean = 6000, sd = 780),  
            rnorm(30, mean = 6500, sd = 590),  
            rnorm(30, mean = 7000, sd = 610)))

data <- tibble(Study, Studytype, Group, Values)

# build the statistical data frame 

stat.test <- data %>%
    group_by(Study) %>%
    wilcox_test(Values ~ Group, ref.group = "CTR") %>%
    add_significance("p")
stat.test <- stat.test %>%
    add_xy_position(x = "Study", dodge = 0.8)

# plot the results as a boxplot

ggplot(data, aes(x = Study, y = Values)) + 
    geom_boxplot(aes(fill = Group)) +
    stat_pvalue_manual(stat.test, label = "p") +
    theme(
            panel.background = element_blank() ,
            axis.line= element_line(), 
            legend.key = element_rect(fill = "white")
        )

```
which produces the following output: 

![kassambara_issue](https://user-images.githubusercontent.com/39332056/89917708-6a00d300-dbf9-11ea-87a9-370442bdd728.png)

When removing studies of type Y from the tibble, the output looks as one would expect, with properly aligned brackets. 

Is there a way to align the brackets (change the width and the x-position) manually?

Thanks

**Comment by kassambara** [comment] 2020-09-30 22:38
Hi, thank you for pointing this out. The root cause was in the rstatix package. Fixed now in the rstatix dev version (https://github.com/kassambara/rstatix/issues/73).

You can install the latest dev version to test:

```r
devtools::install_github("kassambara/rstatix")
devtools::install_github("kassambara/ggpubr")
```

**Closed** 2020-09-30 22:38 UTC
